{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "transit.fullname" . }}
  labels:
    {{- include "transit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "transit.fullname" . }}-api
                port: { number: {{ .Values.api.service.port }} }
    - host: {{ .Values.ingress.exporter.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "transit.fullname" . }}-exporter
                port: { number: {{ .Values.exporter.service.port }} }
    - host: {{ .Values.ingress.portal.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "transit.fullname" . }}-portal
                port: { number: {{ .Values.portal.service.port }} }
{{- end }}
