name: transit_maps
description: Map abstraction for Transit with MapLibre default provider.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.20.0

flutter:
